// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR-eQjXLZu-EeZrAuLnFI75FxI_KrbwvM',
    appId: '1:551655012145:web:2530e1cc2241cbb76de210',
    messagingSenderId: '551655012145',
    projectId: 'mae-assignment-fbf6c',
    authDomain: 'mae-assignment-fbf6c.firebaseapp.com',
    storageBucket: 'mae-assignment-fbf6c.firebasestorage.app',
    measurementId: 'G-8LX6STN88L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoCEK_lBXteBAEB2gpWcD9jLm7EBLP83M',
    appId: '1:551655012145:android:b3cd6cd4e186605c6de210',
    messagingSenderId: '551655012145',
    projectId: 'mae-assignment-fbf6c',
    storageBucket: 'mae-assignment-fbf6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8xJWrH8F2o3BPOGhI2l2ijjBsxqtuSBc',
    appId: '1:551655012145:ios:3faed855d96350f36de210',
    messagingSenderId: '551655012145',
    projectId: 'mae-assignment-fbf6c',
    storageBucket: 'mae-assignment-fbf6c.firebasestorage.app',
    iosBundleId: 'com.example.foodiebox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8xJWrH8F2o3BPOGhI2l2ijjBsxqtuSBc',
    appId: '1:551655012145:ios:3faed855d96350f36de210',
    messagingSenderId: '551655012145',
    projectId: 'mae-assignment-fbf6c',
    storageBucket: 'mae-assignment-fbf6c.firebasestorage.app',
    iosBundleId: 'com.example.foodiebox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR-eQjXLZu-EeZrAuLnFI75FxI_KrbwvM',
    appId: '1:551655012145:web:f4ec3dcd666df2486de210',
    messagingSenderId: '551655012145',
    projectId: 'mae-assignment-fbf6c',
    authDomain: 'mae-assignment-fbf6c.firebaseapp.com',
    storageBucket: 'mae-assignment-fbf6c.firebasestorage.app',
    measurementId: 'G-EB8SHMFRLH',
  );
}
