// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfbbqY5pf_aifjXWsoTczRPGatLr9NIKk',
    appId: '1:538813940991:web:0b8be991641e5554c0f8ca',
    messagingSenderId: '538813940991',
    projectId: 'foodiebox-app',
    authDomain: 'foodiebox-app.firebaseapp.com',
    storageBucket: 'foodiebox-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_EA1vc4oHFIV69ZNDYU_UbQhr_fGZDvQ',
    appId: '1:538813940991:android:e22978d9eab4444ac0f8ca',
    messagingSenderId: '538813940991',
    projectId: 'foodiebox-app',
    storageBucket: 'foodiebox-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsSqVPQFraOPxV6ER3MFwtiJKoqGXcXiQ',
    appId: '1:538813940991:ios:21fffea9d7bf72f8c0f8ca',
    messagingSenderId: '538813940991',
    projectId: 'foodiebox-app',
    storageBucket: 'foodiebox-app.firebasestorage.app',
    iosBundleId: 'com.example.foodiebox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsSqVPQFraOPxV6ER3MFwtiJKoqGXcXiQ',
    appId: '1:538813940991:ios:21fffea9d7bf72f8c0f8ca',
    messagingSenderId: '538813940991',
    projectId: 'foodiebox-app',
    storageBucket: 'foodiebox-app.firebasestorage.app',
    iosBundleId: 'com.example.foodiebox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfbbqY5pf_aifjXWsoTczRPGatLr9NIKk',
    appId: '1:538813940991:web:e4f000102124e5d3c0f8ca',
    messagingSenderId: '538813940991',
    projectId: 'foodiebox-app',
    authDomain: 'foodiebox-app.firebaseapp.com',
    storageBucket: 'foodiebox-app.firebasestorage.app',
  );
}
